SjxSubham/Leetcode

567. Permutation in String.cpp

Added 567. Permutation in String

Create 567. Permutation in String.cpp

---

2583. Kth Largest Sum in a Binary Tree.cpp

2583. Kth Largest Sum in a Binary Tree.cpp

---

950.Reveal cards in Increasing order.cpp

 950.Reveal cards in Increasing order.cpp

---

226. Invert Binary Tree

Added 226. Invert Binary Tree in C++.

Added 226. Invert Binary Tree

---

1046. Last Stone Weight
1046. Last Stone Weight.cpp

1046. Last Stone Weight

---

731. My Calender II

731. My Calendar II

---

322. Coin Change.cpp

this is the solution of coin change question on leetcode
Issue #8  solved
added medium

322. Coin Change.cpp

---

731. My Calender II.cpp

add the solution of the my calender II question on leetcode
issue #1 solved
added a medium problem

731. My Calender II.cpp

---

105. Construct Binary Tree from Preorder and Inorder Traversal.cpp

add the solution of leetcode question number 105
issue #15 solved
added easy question

105. Construct Binary Tree from Preorder and Inorder Traversal.cpp

---

17. Letter Combinations of a Phone Number.cpp

add the solution of Letter Combinations of a Phone Number question on leetcode
issue #18 solved
added medium question

17. Letter Combinations of a Phone Number.cpp

---

3487. Maximum Unique Subarray Sum After Deletion.cpp

**Approach**
Use a HashSet (unordered_set) to store unique positive numbers.
Ensures no duplicates, so we maximize uniqueness.
Track the maximum negative while traversing.
Return result:
If set is non-empty → sum of unique positives.
Else → return the maximum negative.
**Intuition**
Pick all unique positive numbers to maximize the sum. If no positives exist, the best we can do is take the maximum negative element.
**Solution in Code (C++)**
class Solution {
public:
int maxSum(vector<int>& nums) {
unordered_set<int> s;
int temp = INT_MIN;
for(int i: nums){
if(i>0) s.insert(i);
else{
temp = max(temp,i);
}
}
return s.empty()?temp:accumulate(s.begin(), s.end(), 0);
}
};

Solving 3487. Maximum Unique Subarray Sum After Deletion

---

966. Vowel Spellchecker.cpp

**Approach**
The problem requires checking queries against a dictionary (wordlist) under three matching rules (priority order):
Exact Match → If query is exactly in wordlist, return it.
Case-Insensitive Match → If query differs only by case, return the first such word from wordlist.
Vowel Error Match → If query differs only by vowels (i.e., treating vowels as the same), return the first such word from wordlist.
Otherwise → Return "".
Your solution builds three efficient lookup structures:
unordered_set exactMatchSet → For fast exact word lookups.
unordered_map caseInsensitiveMap → Maps lowercase words to their original word (handles case-insensitive match).
unordered_map vowelInsensitiveMap → Maps lowercase words with all vowels replaced by * to their original word (handles vowel-error …

966. Vowel Spellchecker

---

53. Maximum Subarray.cpp

1️⃣ Brute Force
**Approach:**
Try all possible subarrays and calculate their sum. Keep track of the maximum sum found.
**Intuition:**
We generate every subarray starting from each index and expand it to the right. This ensures that we check all possible subarrays.
Simple to understand.
Extremely inefficient because it recomputes sums repeatedly.
2️⃣ Prefix Sum
**Approach:**
Precompute prefix sums to get subarray sums in O(1). For every pair (i, j), calculate subarray sum as prefix[j+1] - prefix[i].
**Intuition:**
Instead of recalculating sums for every subarray, use prefix sums to quickly compute subarray sum ranges.
Still O(n²) because we try all pairs.
Saves recomputation compared to brute force.
3️⃣ Divide & Conquer
**Approach:**
Divide the array into two halves. The maximum subarray …

53. Maximum Subarray.cpp [Multiple Approaches ]

---

3100. Water Bottles II.cpp

Intuition :-
We can simulate the process: drink all current bottles → they become empty.
If we have enough empty bottles, exchange them for one new full bottle, drink it, and repeat.
Since the exchange cost increases each time, eventually we won’t be able to exchange anymore.
Approach :-
Start with numBottles as the initial drunk count and empty bottles.
While emptyBottles ≥ numExchange:
Exchange numExchange empties for 1 full bottle.
Drink it (increase drunk count).
Update empty bottles (-numExchange + 1).
Increment numExchange (cost increases).
Return the total drunk bottles.
Complexity :-
Time Complexity: O(n) (each exchange step simulated)
Space Complexity: O(1)

modified Water Bottles II.cpp

---

37. Sudoku Solver.cpp
53. Maximum Subarray.cpp

**Approach: Backtracking**
I use a backtracking algorithm to fill the empty cells ('.') one by one with digits '1' to '9'.
For each empty cell, try all possible digits.
Before placing, check if it's valid (row, column, and 3×3 subgrid rules).
If valid → place it, then recursively try to solve the rest.
If no digit works → backtrack (undo placement and try another option).
If all cells are filled correctly → solution is found.
This ensures we systematically explore possibilities until we reach the correct valid Sudoku configuration.
**Intuition**
Think of Sudoku solving as filling a puzzle step by step with trial and error:
Whenever you see an empty cell, you test numbers just like a human would.
If the number violates Sudoku rules, skip it.
If a number works, assume it’s correct and move …

43.Sudoku Solver

---

1323. Maximum 69 Number.cpp

Intuition :-
The number consists only of digits 6 and 9. To maximize the number, we should change the first occurrence of 6 into a 9. This guarantees the largest possible value since the leftmost digit contributes the most to the number’s magnitude.
Approach :-
1) Convert the integer to a string (or work with digits).
2) Scan from left to right.
3) On encountering the first 6, change it to 9.
4) Convert back to integer and return.
5) If no 6 is found, return the number unchanged.

1323. Maximum 69 Number.cpp

---

342. Power of Four.cpp

fixes #48
The solution uses bit manipulation to efficiently check if a number is a power of four in constant time. 
It combines three essential conditions:
1. Positive Number Check (n>0)
2. Power of Two Check: (n & (n - 1)) == 0
3. Even Bit Position Check: (n & 0xAAAAAAAA) == 0
- Understanding Powers of Four in Binary
- Powers of four have a unique binary pattern:
4⁰ = 1 = 1 (bit position 0)
4¹ = 4 = 100 (bit position 2)
4² = 16 = 10000 (bit position 4)
4³ = 64 = 1000000 (bit position 6)
- Time Complexity: O(1)
- Space Complexity: O(1)

342. power of four

---

875.Koko Eating Bananas

**Approach : -** 
Search Space Definition:
Koko’s eating speed k must be between 1 and max(piles).
If k = 1, it takes the longest time (sum of all bananas).
If k = max(piles), Koko can finish each pile in 1 hour at most.
Binary Search on Answer:
Use binary search on k in range [1, max(piles)].
For each mid speed, check if Koko can finish all bananas within h hours.
Check Function:
For each pile, hours needed = ceil(pile / k).
Sum up across piles → total hours.
If total hours ≤ h, then speed k is possible.
Otherwise, increase speed.
**Result:**
Find the minimum k where condition is satisfied.
**Intuition**
This is a Binary Search on Answer problem:
The feasible region is monotonic → if Koko can finish at speed k, she can also finish at any speed > k.
Thus we shrink the search space using …

875.Koko Eating Bananas

---

1912. Design Movie Rental System.cpp

**Approach :**
Maintain three data structures:
A map from (shop, movie) → price (to quickly know the price when renting or dropping).
For each movie, a sorted set of available/unrented copies, storing (price, shop). This lets you do search(movie) by taking the first up to 5 entries.
A global sorted set of rented copies, storing (price, shop, movie). This lets you do report() by taking the first up to 5 entries.
On rent(shop, movie):
• Look up the price.
• Remove (price, shop) from the available set for that movie.
• Insert (price, shop, movie) into the rented set.
On drop(shop, movie): do the reverse: remove from rented, reinsert into available.
On search(movie): return the first up to 5 shops from the available set for that movie.
On report(): return the first up to 5 (shop, movie) from …

1912. Design Movie Rental System.cpp

---

2327. Number of People Aware of a Secret.cpp

**Approach**
Base Case:
On day 1, one person knows the secret → dp[1] = 1.
Sliding Window to Track Spreaders:
Maintain a running sum window = number of people who are currently in the "sharing phase" (they know the secret and are allowed to spread).
When someone reaches delay days, they enter the window (can start sharing).
When someone reaches forget days, they exit the window (they forget the secret).
Formula inside loop:
enter = i - delay → people who just become eligible to share.
exit = i - forget → people who forget today and must be removed.
Update window accordingly.
dp[i] = window → all active sharers pass the secret to new people today.
Final Answer:
At day n, not everyone still remembers (some already forgot).
So we only sum contributions from people who haven’t forgotten:
for …

2327. Number of People Aware of a Secret.cpp

---

991. Broken Calculator.cpp

[Leetcode 991 - Broken Calculator](https://leetcode.com/problems/broken-calculator/)
---
At first glance, it may seem natural to simulate operations **forward** from `startValue` to `target`. But when `target` is much larger, this results in a brute-force and inefficient approach.
Instead, we reverse the problem:
- Start from `target` and work backward toward `startValue`.
- In reverse:
- If the `target` is **even**, it must have been obtained by a **double** operation → so we divide by 2.
- If the `target` is **odd**, it must have been obtained by decrementing after a double → so we increment it to make it even.
This greedy reverse approach helps reduce the problem size quickly.
---
1. While `target > startValue`:
- If `target` is **odd**: increment it (`target++`)
- If `target` is …

991. Broken Calculator

---

2942. Find Words Containing Character.cpp

We are given a list of words and a character x.
We need to find all the indices of words that contain the character x.
Now we need to Go through the each word one by one, Check each character in the word.
If the word contains x, then it store its index in the answer list.
We Use a break to avoid checking the rest of that word once the character is found which helps in saving our time.
Firstly we need to Initialize an empty vector ans to store the indices of valid words then,Iterate through each word in the vector words using index i.
For each word, iterate through its characters using index j.
If words[i][j] == x, push the index i into ans and break to move to the next word and finally After all iterations, return the vector ans as the result. 
```cpp
class Solution {
public:
vector<int> …
```

2942. Find Words Containing Character
